# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  system.debug: 'true'
  webAppName: huongttt13-devops-project2
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'Flask'
  vmImageName: 'ubuntu-latest'
steps:
- script: echo Hello, Huong!
  displayName: "Run"